# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
