# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0003_auto_20160624_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='topclass',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='labelname',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='subclass',
            old_name='name',
            new_name='subclass',
        ),
    ]
