# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0004_auto_20160624_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='topclass',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='labelname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='filename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subclass',
            old_name='subclass',
            new_name='name',
        ),
    ]
