# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0005_auto_20160624_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
