# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0006_story_annotated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotator',
            old_name='firstName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='annotator',
            old_name='lastName',
            new_name='username',
        ),
    ]
