# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0007_auto_20160627_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.CharField(default='#ff0000', max_length=50),
        ),
    ]
