# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0008_class_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.Annotator')),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='annotated',
        ),
        migrations.AddField(
            model_name='complete',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.Story'),
        ),
    ]
